# Generated by Django 5.2.7 on 2025-11-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='game_comments.gamecomment'),
        ),
        migrations.AddIndex(
            model_name='gamecomment',
            index=models.Index(fields=['parent'], name='game_commen_parent__b5b8c6_idx'),
        ),
    ]
