# Generated by Django 5.2.6 on 2025-11-04 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('game_mode', models.CharField(choices=[('classic_1v1', 'Classic 1v1'), ('tournament', 'Tournament'), ('boss_fight', 'Boss Fight')], default='classic_1v1', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('max_players', models.IntegerField(default=2)),
                ('round_duration', models.IntegerField(default=60, help_text='Round duration in seconds')),
                ('cards_per_turn', models.IntegerField(default=5, help_text='Cards drawn per turn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_gt_lobbies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lobbies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LobbyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_username', models.CharField(blank=True, max_length=50, null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='zawomons_gt.lobby')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gt_lobby_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('lobby', 'guest_username'), ('lobby', 'user')},
            },
        ),
    ]
