# Generated by Django 5.2.6 on 2025-11-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zawomons_gt', '0002_alter_lobby_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='cards_per_turn',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='round_duration',
        ),
    ]
