# Generated by Django 5.2.4 on 2025-08-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
    ]
