# Generated by Django 5.2.4 on 2025-08-25 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20250825_2020'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_element', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('earth', 'Earth'), ('air', 'Air'), ('light', 'Light'), ('dark', 'Dark'), ('nature', 'Nature'), ('electric', 'Electric')], max_length=20)),
                ('secondary_element', models.CharField(blank=True, choices=[('fire', 'Fire'), ('water', 'Water'), ('earth', 'Earth'), ('air', 'Air'), ('light', 'Light'), ('dark', 'Dark'), ('nature', 'Nature'), ('electric', 'Electric')], max_length=20, null=True)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('experience', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('max_energy', models.IntegerField(default=50)),
                ('current_energy', models.IntegerField(default=50)),
                ('damage', models.IntegerField(default=25)),
                ('initiative', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='default-game', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='unity_build_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CreatureLearningSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_id', models.IntegerField()),
                ('start_time_utc', models.DateTimeField()),
                ('end_time_utc', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_spells', to='games.creature')),
            ],
            options={
                'unique_together': {('creature', 'spell_id')},
            },
        ),
        migrations.CreateModel(
            name='CreatureSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_id', models.IntegerField()),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_spells', to='games.creature')),
            ],
            options={
                'unique_together': {('creature', 'spell_id')},
            },
        ),
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gold', models.IntegerField(default=100)),
                ('wood', models.IntegerField(default=50)),
                ('stone', models.IntegerField(default=25)),
                ('gems', models.IntegerField(default=5)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='creature',
            name='player_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatures', to='games.playerdata'),
        ),
        migrations.DeleteModel(
            name='GameSave',
        ),
        migrations.AddIndex(
            model_name='playerdata',
            index=models.Index(fields=['user', 'game'], name='games_playe_user_id_8fc7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdata',
            index=models.Index(fields=['last_played'], name='games_playe_last_pl_f91112_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerdata',
            unique_together={('user', 'game')},
        ),
    ]
