# Generated by Django 5.2.4 on 2025-08-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_creature_game_created_at_game_is_active_game_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdata',
            name='name',
        ),
    ]
