# Generated by Django 5.2.4 on 2025-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_name_from_playerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='can_claim_start_creature',
            field=models.BooleanField(default=True),
        ),
    ]
