# Generated by Django 5.2.4 on 2025-08-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_creature_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='main_element',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='creature',
            name='secondary_element',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
