# Generated by Django 5.2.4 on 2025-08-30 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_creature_main_element_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creaturelearningspell',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='creaturelearningspell',
            name='creature',
        ),
        migrations.RemoveField(
            model_name='creaturespell',
            name='learned_at',
        ),
        migrations.AddField(
            model_name='creaturespell',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='creaturespell',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='creaturespell',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creaturespell',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='creaturespell',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='creaturespell',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='games.creature'),
        ),
        migrations.AddIndex(
            model_name='creaturespell',
            index=models.Index(fields=['creature', 'is_learned'], name='games_creat_creatur_be3de9_idx'),
        ),
        migrations.AddIndex(
            model_name='creaturespell',
            index=models.Index(fields=['end_time'], name='games_creat_end_tim_cf957e_idx'),
        ),
        migrations.DeleteModel(
            name='CreatureLearningSpell',
        ),
    ]
