# Generated by Django 5.2.4 on 2025-08-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_creaturelearningspell_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creaturespell',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='creaturespell',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
