from django.urls import path
from .views import (ZawomonsPlayerDataGetView,
                   ZawomonsSetSingleResourceView, ZawomonsPlayersListView,
                   ZawomonsFriendsListView, ZawomonsCreatureGetView,
                   ZawomonsCreatureAddView, ZawomonsCreatureSetView,
                   ZawomonsSpellLearnView, ZawomonsSpellCompleteView)

urlpatterns = [
    # general endpoints
    path('zawomons/players/', ZawomonsPlayersListView.as_view(), name='zawomons-players-list'),
    path('zawomons/friends/', ZawomonsFriendsListView.as_view(), name='zawomons-friends-list'),

    # player endpoints
    path('zawomons/player-data-get/', ZawomonsPlayerDataGetView.as_view(), name='zawomons-player-data-get'),
    path('zawomons/set-single-resource/', ZawomonsSetSingleResourceView.as_view(), name='zawomons-set-single-resource'),

    # creature endpoints
    path('zawomons/creature-get/<int:creature_id>/', ZawomonsCreatureGetView.as_view(), name='zawomons-creature-get'),
    path('zawomons/creature-add/', ZawomonsCreatureAddView.as_view(), name='zawomons-creature-add'),
    path('zawomons/creature-set/', ZawomonsCreatureSetView.as_view(), name='zawomons-creature-set'),

    # spell endpoints
    path('zawomons/spell-learn/', ZawomonsSpellLearnView.as_view(), name='zawomons-spell-learn'),
    path('zawomons/spell-complete/', ZawomonsSpellCompleteView.as_view(), name='zawomons-spell-complete'),
]


# --- 1. player endpoints
# ✅ GET  /zawomons/players/ - global player list (ale nie wszystkie ich dane tylko niektóre dla krótszego payloadu (do listy znajomych potrzebne)
# ✅ GET  /zawomons/players/me/ - pobiera wszystkie dane gracza w tym: listę creatures, listę cities, ilości zasobów, experience, last_creature_claim_time (raz na starcie gry dla synchronizacji klienta z backendem)
# ✅ GET  /zawomons/players/me/friends/ - friend list (podobnie jak global player list nie wszystkie dane tylko friend list)
# ✅ GET  /zawomons/players/me/tasks/ - all ongoing tasks for the player (all creatures + all cities) (e.g., travel, learning, merging, city upgrade etc.)

# - a) other player endpoints (read-only)
# ✅ GET  /zawomons/players/<id>/ - pobranie danych innego gracza po kliknięciu w jego profil w grze
# ✅ GET  /zawomons/players/<id>/creatures/ - lista stworków innego gracza (do podglądu profilu)
# ✅ GET  /zawomons/players/<id>/cities/ - lista miast innego gracza (do podglądu profilu)
# ✅ GET  /zawomons/players/<id>/battles/ - lista bitew innego gracza (do podglądu profilu)

# - b) me player creature endpoints
# ✅ GET  /zawomons/players/me/creatures/ - lista stworków gracza
# ✅ GET  /zawomons/players/me/creatures/<id>/ - pobiera dane danego stworka gracza (jeśli należy do gracza)
# ✅ GET  /zawomons/players/me/creatures/<id>/progress/ - pobiera tylko progress taska (jeśli stworek należy do gracza) - np. ile zostało do końca nauki spella, podróży itp.

# ✅ PUT  /zawomons/players/me/creatures/<id>/ - aktualizuje naszego stworka, na przykład zmienia jego nazwę (ale nie statystyki)

# ✅ POST /zawomons/players/me/creatures/claim/ - robi próbę dodania darmowego stworka jeśli minęły 4h od ostatniego last_creature_claim_time w player data
# ✅ POST /zawomons/players/me/creatures/merge/ - łączy dwa stworki w jeden (jeśli oba należą do gracza i mają ten sam main_element i wystarczająco dużo doświadczenia)
# ✅ POST /zawomons/players/me/creatures/<id>/spells/learn/ - zaczyna naukę spella (jeśli stworek nie uczy się już innego spella, ma zasoby gracz i stworek ma wystarczająco dużo energii)
# ✅ POST /zawomons/players/me/creatures/<id>/travel/start/ - zaczyna podróż (jeśli stworek nie jest już w podróży, ma zasoby gracz i stworek ma wystarczająco dużo energii)

# - c) me player city endpoints
# ✅ GET  /zawomons/players/me/cities/ - lista miast gracza
# ✅ GET  /zawomons/players/me/cities/<id>/ - pobiera dane danego miasta gracza
# ✅ GET  /zawomons/players/me/cities/<id>/progress/ - pobiera tylko progress taska (jeśli miasto należy do gracza) - np. ile zostało do końca budowy, ulepszenia itp.

# ✅ PUT  /zawomons/players/me/cities/<id>/ - aktualizuje miasto, na przykład zmienia jego nazwę (ale nie statystyki)

# ✅ POST /zawomons/players/me/cities/build - buduje nowe miasto (jeśli gracz ma wystarczająco dużo zasobów)
# ✅ POST /zawomons/players/me/cities/<id>/upgrade/ - ulepsza miasto (jeśli należy do gracza i ma wystarczająco dużo zasobów)
# ✅ POST /zawomons/players/me/cities/<id>/resources/collect/ - claim resources generated by a city

# - d) me player battle endpoints
# ✅ GET  /zawomons/players/me/battles/ - lista bitew gracza (zarówno zakończonych jak i trwających)

# --- 2. public endpoints (read-only for all, unless stated otherwise)
# ✅ GET  /zawomons/creatures/ - lista wszystkich stworków (dzikich i należących do graczy)
# ✅ GET  /zawomons/creatures/<id>/ - pobiera dane danego stworka (dowolnego nie tylko danego gracza)

# ✅ GET  /zawomons/cities/ - lista miast (wszystkich)
# ✅ GET  /zawomons/cities/<id>/ - pobiera dane danego miasta (dowolnego nie tylko danego gracza)

# ✅ GET  /zawomons/spells/ - lista wszystkich spelli w grze (statyczna)

# ✅ GET  /zawomons/battles/ - lista wszystkich bitew (publicznych i prywatnych)
# ✅ GET  /zawomons/battles/<id>/ - pobiera dane danej bitwy


