# Generated by Django 5.2.6 on 2025-10-13 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('battle_type', models.CharField(choices=[('friendly', 'Friendly Match'), ('ranked', 'Ranked Battle')], default='friendly', max_length=10)),
                ('phase', models.CharField(choices=[('waiting', 'Waiting for players'), ('selection', 'Move selection'), ('combat', 'Combat execution'), ('finished', 'Battle finished')], default='waiting', max_length=10)),
                ('current_turn', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('spell_img', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=100)),
                ('wood', models.IntegerField(default=50)),
                ('stone', models.IntegerField(default=25)),
                ('gems', models.IntegerField(default=5)),
                ('experience', models.IntegerField(default=0)),
                ('last_creature_claim_time', models.DateTimeField(blank=True, null=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_type', models.CharField(choices=[('friendly', 'Friendly Battle'), ('ranked', 'Ranked Battle')], default='friendly', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('sender_creatures', models.JSONField(default=list, help_text='Lista ID creatures wybranych przez wysyłającego')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zawomons.battle')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='zawomons.player')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='zawomons.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_element', models.CharField(max_length=20)),
                ('secondary_element', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(default='#FF00DD', max_length=7)),
                ('experience', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('max_energy', models.IntegerField(default=50)),
                ('current_energy', models.IntegerField(default=50)),
                ('damage', models.IntegerField(default=25)),
                ('initiative', models.IntegerField(default=10)),
                ('posX', models.FloatField(default=0.0)),
                ('posY', models.FloatField(default=0.0)),
                ('travel_from_x', models.FloatField(blank=True, null=True)),
                ('travel_from_y', models.FloatField(blank=True, null=True)),
                ('travel_to_x', models.FloatField(blank=True, null=True)),
                ('travel_to_y', models.FloatField(blank=True, null=True)),
                ('travel_start_time', models.DateTimeField(blank=True, null=True)),
                ('travel_end_time', models.DateTimeField(blank=True, null=True)),
                ('travel_is_complete', models.BooleanField(default=False)),
                ('learning_spell_id', models.IntegerField(blank=True, null=True)),
                ('learning_start_time', models.DateTimeField(blank=True, null=True)),
                ('learning_end_time', models.DateTimeField(blank=True, null=True)),
                ('learning_is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatures', to='zawomons.player')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posX', models.FloatField()),
                ('posY', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='zawomons.player')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_battles_as_player1', to='zawomons.player'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websocket_battles_as_player2', to='zawomons.player'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websocket_won_battles', to='zawomons.player'),
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField()),
                ('current_energy', models.IntegerField()),
                ('initiative_bonus', models.IntegerField(default=0)),
                ('has_confirmed_move', models.BooleanField(default=False)),
                ('team', models.IntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='zawomons.battle')),
                ('selected_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zawomons.battleparticipant')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawomons.creature')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawomons.player')),
                ('selected_spell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zawomons.spell')),
            ],
        ),
        migrations.CreateModel(
            name='BattleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('action_order', models.IntegerField()),
                ('action_type', models.CharField(choices=[('spell_cast', 'Spell Cast'), ('damage_dealt', 'Damage Dealt'), ('heal_performed', 'Heal Performed'), ('buff_applied', 'Buff Applied')], max_length=20)),
                ('damage_amount', models.IntegerField(default=0)),
                ('heal_amount', models.IntegerField(default=0)),
                ('initiative_bonus', models.IntegerField(default=0)),
                ('damage_bonus', models.IntegerField(default=0)),
                ('target_hp_after', models.IntegerField(blank=True, null=True)),
                ('target_alive_after', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='zawomons.battle')),
                ('caster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_performed', to='zawomons.battleparticipant')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_received', to='zawomons.battleparticipant')),
                ('spell_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zawomons.spell')),
            ],
        ),
        migrations.CreateModel(
            name='CreatureSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_spells', to='zawomons.creature')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawomons.spell')),
            ],
            options={
                'unique_together': {('creature', 'spell')},
            },
        ),
    ]
