# Generated by Django 5.2.4 on 2025-09-23 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=100)),
                ('wood', models.IntegerField(default=50)),
                ('stone', models.IntegerField(default=25)),
                ('gems', models.IntegerField(default=5)),
                ('experience', models.IntegerField(default=0)),
                ('can_claim_start_creature', models.BooleanField(default=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_element', models.CharField(max_length=20)),
                ('secondary_element', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('experience', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('max_energy', models.IntegerField(default=50)),
                ('current_energy', models.IntegerField(default=50)),
                ('damage', models.IntegerField(default=25)),
                ('initiative', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_creatures', to=settings.AUTH_USER_MODEL)),
                ('player_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatures', to='zawomons.playerdata')),
            ],
        ),
        migrations.CreateModel(
            name='CreatureSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_learned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='zawomons.creature')),
            ],
            options={
                'indexes': [models.Index(fields=['creature', 'is_learned'], name='zawomons_cr_creatur_7eafd0_idx'), models.Index(fields=['end_time'], name='zawomons_cr_end_tim_017233_idx')],
                'unique_together': {('creature', 'spell_id')},
            },
        ),
        migrations.AddIndex(
            model_name='playerdata',
            index=models.Index(fields=['user', 'game'], name='zawomons_pl_user_id_7671c0_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdata',
            index=models.Index(fields=['last_played'], name='zawomons_pl_last_pl_4a6ac7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerdata',
            unique_together={('user', 'game')},
        ),
    ]
