# Generated by Django 5.2.4 on 2025-09-27 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('spell_img', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=100)),
                ('wood', models.IntegerField(default=50)),
                ('stone', models.IntegerField(default=25)),
                ('gems', models.IntegerField(default=5)),
                ('experience', models.IntegerField(default=0)),
                ('last_creature_claim_time', models.DateTimeField(blank=True, null=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_element', models.CharField(max_length=20)),
                ('secondary_element', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(default='#FF00DD', max_length=7)),
                ('experience', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('max_energy', models.IntegerField(default=50)),
                ('current_energy', models.IntegerField(default=50)),
                ('damage', models.IntegerField(default=25)),
                ('initiative', models.IntegerField(default=10)),
                ('posX', models.FloatField(default=0.0)),
                ('posY', models.FloatField(default=0.0)),
                ('travel_from_x', models.FloatField(blank=True, null=True)),
                ('travel_from_y', models.FloatField(blank=True, null=True)),
                ('travel_to_x', models.FloatField(blank=True, null=True)),
                ('travel_to_y', models.FloatField(blank=True, null=True)),
                ('travel_start_time', models.DateTimeField(blank=True, null=True)),
                ('travel_end_time', models.DateTimeField(blank=True, null=True)),
                ('travel_is_complete', models.BooleanField(default=False)),
                ('learning_spell_id', models.IntegerField(blank=True, null=True)),
                ('learning_start_time', models.DateTimeField(blank=True, null=True)),
                ('learning_end_time', models.DateTimeField(blank=True, null=True)),
                ('learning_is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatures', to='zawomons.player')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posX', models.FloatField()),
                ('posY', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='zawomons.player')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('player1_win', 'Player 1 Wins'), ('player2_win', 'Player 2 Wins'), ('draw', 'Draw'), ('ongoing', 'Ongoing')], default='ongoing', max_length=20)),
                ('battle_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_player1', to='zawomons.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_player2', to='zawomons.player')),
            ],
        ),
        migrations.CreateModel(
            name='CreatureSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_spells', to='zawomons.creature')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawomons.spell')),
            ],
            options={
                'unique_together': {('creature', 'spell')},
            },
        ),
    ]
