# Generated by Django 5.2.4 on 2025-09-23 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawomons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('spell_img', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='playerdata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playerdata',
            name='game',
        ),
        migrations.RemoveField(
            model_name='playerdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='player_data',
        ),
        migrations.AddField(
            model_name='creature',
            name='learning_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='learning_is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creature',
            name='learning_spell_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='learning_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='posX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creature',
            name='posY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creature',
            name='travel_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='travel_from_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='travel_from_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='travel_is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creature',
            name='travel_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='travel_to_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='travel_to_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creature',
            name='color',
            field=models.CharField(default='#FF00DD', max_length=7),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=100)),
                ('wood', models.IntegerField(default=50)),
                ('stone', models.IntegerField(default=25)),
                ('gems', models.IntegerField(default=5)),
                ('experience', models.IntegerField(default=0)),
                ('last_creature_claim_time', models.DateTimeField(blank=True, null=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posX', models.FloatField()),
                ('posY', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='zawomons.player')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('player1_win', 'Player 1 Wins'), ('player2_win', 'Player 2 Wins'), ('draw', 'Draw'), ('ongoing', 'Ongoing')], default='ongoing', max_length=20)),
                ('battle_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_player1', to='zawomons.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_player2', to='zawomons.player')),
            ],
        ),
        migrations.AlterField(
            model_name='creature',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatures', to='zawomons.player'),
        ),
        migrations.DeleteModel(
            name='CreatureSpell',
        ),
        migrations.DeleteModel(
            name='PlayerData',
        ),
    ]
