# Generated by Django 5.2.6 on 2025-10-13 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawomons', '0002_remove_battle_battle_data_remove_battle_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_type', models.CharField(choices=[('friendly', 'Friendly Battle'), ('ranked', 'Ranked Battle')], default='friendly', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('sender_creatures', models.JSONField(default=list, help_text='Lista ID creatures wybranych przez wysyłającego')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zawomons.battle')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='zawomons.player')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='zawomons.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
