# Generated by Django 5.2.4 on 2025-09-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawomons', '0002_spell_alter_playerdata_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_spells', to='zawomons.creature')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawomons.spell')),
            ],
            options={
                'unique_together': {('creature', 'spell')},
            },
        ),
    ]
